export const PHONE_EXTENSIONS = [
  "+1",
  "+44",
  "+61",
  "+49",
  "+33",
  "+39",
  "+34",
  "+81",
  "+86",
  "+91",
  "+55",
  "+27",
  "+971",
  "+852",
  "+65",
  "+64",
]

export const currencyNames = {
  USD: "US Dollar",
  EUR: "Euro",
  GBP: "British Pound",
  CAD: "Canadian Dollar",
  AUD: "Australian Dollar",
  JPY: "Japanese Yen",
  CHF: "Swiss Franc",
  CNY: "Chinese Yuan",
  SEK: "Swedish Krona",
  NOK: "Norwegian Krone",
  DKK: "Danish Krone",
  PLN: "Polish Zloty",
  CZK: "Czech Koruna",
  HUF: "Hungarian Forint",
  RON: "Romanian Leu",
  BGN: "Bulgarian Lev",
  HRK: "Croatian Kuna",
  RSD: "Serbian Dinar",
  MKD: "Macedonian Denar",
  ALL: "Albanian Lek",
  BAM: "Bosnia-Herzegovina Mark",
  ISK: "Icelandic Krona",
  MDL: "Moldovan Leu",
  UAH: "Ukrainian Hryvnia",
  BYN: "Belarusian Ruble",
  RUB: "Russian Ruble",
  TRY: "Turkish Lira",
  ILS: "Israeli Shekel",
  AED: "UAE Dirham",
  SAR: "Saudi Riyal",
  QAR: "Qatari Riyal",
  KWD: "Kuwaiti Dinar",
  BHD: "Bahraini Dinar",
  OMR: "Omani Rial",
  JOD: "Jordanian Dinar",
  LBP: "Lebanese Pound",
  EGP: "Egyptian Pound",
  MAD: "Moroccan Dirham",
  TND: "Tunisian Dinar",
  DZD: "Algerian Dinar",
  ZAR: "South African Rand",
  NGN: "Nigerian Naira",
  GHS: "Ghanaian Cedi",
  KES: "Kenyan Shilling",
  UGX: "Ugandan Shilling",
  TZS: "Tanzanian Shilling",
  ETB: "Ethiopian Birr",
  MUR: "Mauritian Rupee",
  BRL: "Brazilian Real",
  ARS: "Argentine Peso",
  CLP: "Chilean Peso",
  COP: "Colombian Peso",
  PEN: "Peruvian Sol",
  UYU: "Uruguayan Peso",
  VES: "Venezuelan Bolivar",
  MXN: "Mexican Peso",
  GTQ: "Guatemalan Quetzal",
  HNL: "Honduran Lempira",
  NIO: "Nicaraguan Cordoba",
  CRC: "Costa Rican Colon",
  PAB: "Panamanian Balboa",
  DOP: "Dominican Peso",
  JMD: "Jamaican Dollar",
  TTD: "Trinidad & Tobago Dollar",
  BBD: "Barbadian Dollar",
  XCD: "East Caribbean Dollar",
  AWG: "Aruban Florin",
  BZD: "Belize Dollar",
  KYD: "Cayman Islands Dollar",
  SGD: "Singapore Dollar",
  MYR: "Malaysian Ringgit",
  THB: "Thai Baht",
  VND: "Vietnamese Dong",
  IDR: "Indonesian Rupiah",
  PHP: "Philippine Peso",
  KRW: "South Korean Won",
  INR: "Indian Rupee",
  PKR: "Pakistani Rupee",
  BDT: "Bangladeshi Taka",
  LKR: "Sri Lankan Rupee",
  NPR: "Nepalese Rupee",
  MMK: "Myanmar Kyat",
  KHR: "Cambodian Riel",
  LAK: "Lao Kip",
  BND: "Brunei Dollar",
}
